org: mateoespinoza
service: api-destino

provider:
  name: aws
  runtime: nodejs16.x  # Usamos Node.js 14.x
  iam:
    role: arn:aws:iam::399737753482:role/LabRole  # Aquí se asigna el ARN del rol LabRole

  environment:
    DESTINOS_TABLE: ${self:custom.tables.destinos}

custom:
  tables:
    destinos: t_destinos  # Nombre de la tabla DynamoDB para destinos

resources:
  Resources:
    DestinosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tables.destinos}
        AttributeDefinitions:
          - AttributeName: id_destino
            AttributeType: S
          - AttributeName: ciudad
            AttributeType: S
        KeySchema:
          - AttributeName: id_destino
            KeyType: HASH
          - AttributeName: ciudad
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  CrearDestino:
    handler: CrearDestino.handler
    events:
      - http:
          path: /destinos
          method: post
          cors: true

  delete_destino:
    handler: eliminarDestino.handler
    events:
      - http:
          path: /destinos/{id_destino}
          method: delete
          cors: true

  update_destino:
    handler: modificarDestino.handler
    events:
      - http:
          path: /destinos/{id_destino}
          method: put
          cors: true

  get_destino_by_id:
    handler: obtenerDestinoById.handler
    events:
      - http:
          path: /destinos/{id_destino}
          method: get
          cors: true

  get_all_destinos:
    handler: obtenerDestinos.handler
    events:
      - http:
          path: /destinos
          method: get
          cors: true
